name: Create Release
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Install XeLatex
      run: |
        sudo apt-get update
        sudo apt-get install texlive-xetex
        fc-list
    - uses: pandoc/actions/setup@v1
      with:
        version: 2.19
    - run: make pdf
    - uses: actions/upload-artifact@master
      with:
        name: cookbook.pdf
        path: cookbook.pdf

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@master
      with:
        name: cookbook.pdf
        path: cookbook.pdf
    - uses: ncipollo/release-action@v1
      name: Upload PDF File to GitHub
      with:
        artifacts: cookbook.pdf
